### ISSUE TITLE
fido documentation link fails

### ISSUE THREAD

**Issue by lljohnston** [openpreserve/fido#199] opened 2021-04-12 14:37 UTC
We'd like to evaluate fido, which requires a pre-review before the test install. These links are provided for documentation on the wiki, but fails http://wiki.opf-labs.org/display/KB/FIDO+usage+guide and http://wiki.opf-labs.org/display/PT/Fido

**Comment by mistydemeo** [comment] 2021-04-12 23:51
Hm. Looks like the wiki is gone entirely. I think that may have been missed - the OPF site links here for documentation, but we link to that wiki. I'll look into migrating it into the GitHub wiki.

**Comment by carlwilson** [comment] 2021-04-20 13:00
Thanks for reporting this @lljohnston and @mistydemeo, there's been an issue with the Wiki box, and I was a little tardy in noticing. It's back up and working, and I'll see if we can do anything to stabilise /freeze it for now (probably containerise it). I'll close this now as I can confirm both of the reported links are working again.

**Closed** 2021-04-20 13:01 UTC
