### ISSUE TITLE
Problem: Powerpoint in GovDocs select triggering a recursion depth error in olefile.py

### ISSUE THREAD

**Issue by ross-spencer** [openpreserve/fido#132] opened 2018-08-02 19:57 UTC
Noticed by @richardlehane in his Siegfried [benchmark testing](https://www.itforarchivists.com/post/benchmarks/), an exception is being raised in Fido for the attached file. The error:
```
  File "/usr/lib/python2.7/dist-packages/olefile/olefile.py", line 882, in append_kids
    self.append_kids(child.sid_left)
  File "/usr/lib/python2.7/dist-packages/olefile/olefile.py", line 876, in append_kids
    child = self.olefile._load_direntry(child_sid) #direntries[child_sid]
  File "/usr/lib/python2.7/dist-packages/olefile/olefile.py", line 1748, in _load_direntry
    "double reference for OLE stream/storage")
  File "/usr/lib/python2.7/dist-packages/olefile/olefile.py", line 1097, in _raise_defect
    log.warning(message)
  File "/usr/lib/python2.7/logging/__init__.py", line 1185, in warning
    if self.isEnabledFor(WARNING):
  File "/usr/lib/python2.7/logging/__init__.py", line 1373, in isEnabledFor
    return level >= self.getEffectiveLevel()
RuntimeError: maximum recursion depth exceeded
```
Example (zipped): [example-broken.zip](https://github.com/openpreserve/fido/files/2254971/example-broken.zip)

**Comment by mistydemeo** [comment] 2018-08-03 04:03
Interesting, I'll take a look and see what's causing this. Do you know what version of olefile you had installed?

**Comment by ross-spencer** [comment] 2018-08-03 12:39
Good point @mistydemeo! Sorry about that. 

I checked here: 
```
$ pip show olefile
Name: olefile
Version: 0.44
Summary: Python package to parse, read and write Microsoft OLE2 files (Structured Storage or Compound Document, Microsoft Office) - Improved version of the OleFileIO module from PIL, the Python Image Library.
Home-page: https://www.decalage.info/python/olefileio
Author: Philippe Lagadec
Author-email: https://www.decalage.info/contact
License: BSD
Location: /usr/local/lib/python2.7/dist-packages
```
Which prompted me to upgrade with `-U`:
```
$ pip show olefile
Name: olefile
Version: 0.45.1
Summary: Python package to parse, read and write Microsoft OLE2 files (Structured Storage or Compound Document, Microsoft Office) - Improved version of the OleFileIO module from PIL, the Python Image Library.
Home-page: https://www.decalage.info/python/olefileio
Author: Philippe Lagadec
Author-email: nospam@decalage.info
License: BSD
Location: /home/ross-spencer/.local/lib/python2.7/site-packages
```
The problem still exists. 

And Fido:
```
FIDO v1.3.7 (formats-v92.xml, container-signature-20170920.xml, format_extensions.xml)
```

**Comment by mistydemeo** [comment] 2018-08-04 16:50
I can confirm this using the latest olefile, in both Python 2 and Python 3. It can be reproed by doing `olefile.OleFileIO('808724.ppt')`, so there's nothing specific to how Fido is using it. I've opened an upstream issue so hopefully this can get addressed: https://github.com/decalage2/olefile/issues/103

**Comment by mistydemeo** [comment] 2018-08-04 16:55
Looks like there's an upstream PR to fix this: https://github.com/decalage2/olefile/pull/93 I've confirmed that FIDO can process this file if that PR is integrated. Hopefully it gets shipped soon!

**Comment by ross-spencer** [comment] 2018-08-04 18:28
Fingers crossed! Good sleuthing @mistydemeo :)

**Comment by mistydemeo** [comment] 2018-08-23 19:50
OK, this is fixed! Should work fine with the next release of olefile.

**Comment by decalage2** [comment] 2018-08-23 21:34
I tested your PPT file after merging https://github.com/decalage2/olefile/pull/93 : the recursion error is fixed, but other exceptions are raised now. I think the file is quite malformed, or there are other bugs in olefile.

**Comment by OskarPersson** [comment] 2018-09-11 11:18
I tested the PPT file with opf-fido==1.3.7 and olefile==0.46 which works without errors and results in the following:

```
FIDO v1.3.7 (formats-v92.xml, container-signature-20170920.xml, format_extensions.xml)
OK,355,fmt/111,"OLE2 Compound Document Format","OLE2 Compound Document Format",333600,"808724.ppt","None","signature"
FIDO: Processed      1 files in 467.00 msec,  2 files/sec
```

Siegfried results in the same format but emits an error:

```
[FILE] /Users/Oskar/Downloads/example/808724.ppt
[ERROR] mscfb: directory entries read error (mscfb: slicer read error (EOF); 15125504); 15125504
---
siegfried   : 1.4.5
scandate    : 2018-09-11T13:16:52+02:00
signature   : pronom.sig
created     : 2016-02-05T17:41:10+11:00
identifiers :
  - name    : 'pronom'
    details : 'DROID_SignatureFile_V84.xml; container-signature-20160121.xml'
---
filename : '808724.ppt'
filesize : 333600
modified : 2012-07-26T05:54:40+02:00
errors   : 'mscfb: directory entries read error (mscfb: slicer read error (EOF); 15125504); 15125504'
matches  :
  - id      : pronom
    puid    : fmt/111
    format  : 'OLE2 Compound Document Format'
    version :
    mime    :
    basis   : 'byte match at 0, 30'
    warning :
```

Maybe this can be closed since it works in fido?

**Comment by decalage2** [comment] 2018-09-11 12:02
BTW, PowerPoint 2016 cannot open the file, it really looks broken. So it's normal to get parsing errors. oledir shows that there are no proper directory entries, so no data can be read at the OLE/CFB level.

**Comment by ablwr** [comment] 2018-10-01 13:20
Confirmed fixed, closing this!

**Closed by ablwr** 2018-10-01 13:20 UTC
